Failed login attempt with username: sfgsfgs
User not logged in to view update customer
User not logged in to view update customer1
User not logged in to view customer record  1
User not logged in to view customer record  3
User not logged in to view customer record  30
Failed login attempt with username: test
Failed login attempt with username: test1
User not logged in to view update customer 1
Failed login attempt with username: admin
Failed login attempt with username: admin
Failed login attempt with username: admin
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/sam.boothroyd/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/QA-Project/website/views.py", line 107, in home
    is_blocked, attempts_remaining, block_time = check_login_attempts(request, username)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/QA-Project/website/views.py", line 65, in check_login_attempts
    block_time = cache.ttl(block_key)
                 ^^^^^^^^^
  File "/Users/sam.boothroyd/env/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LocMemCache' object has no attribute 'ttl'
"POST / HTTP/1.1" 500 70646
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: test
Failed login attempt with username: admin'; --
User not logged in to view customer record 10
Internal Server Error: /add_customer/
Traceback (most recent call last):
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/.pyenv/versions/3.11.0/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
                    ^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam.boothroyd/Desktop/repositories/srm_project/env/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
